<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExpressionSeeder extends Seeder
{
    public function run(): void
    {
        // Truncate the table to remove existing data
        DB::table('expressions')->truncate();
        
        DB::table('expressions')->insert([
            [
                'expression' => 'Meter la pata',
                'right_answer' => 'To make a mistake',
                'false_answer_one' => 'To have good luck',
                'false_answer_two' => 'To be angry',
                'language' => 'spanish',
                'created_by' => 'admin',
                'is_validated' => true,
                'created_at' => now(),
            ],
            [
                'expression' => 'Estar en las nubes',
                'right_answer' => 'Daydreaming or thinking about something unrelated to reality',
                'false_answer_one' => 'Being very focused on a task',
                'false_answer_two' => 'Feeling light and happy',
                'language' => 'spanish',
                'created_by' => 'admin',
                'is_validated' => true,
                'created_at' => now(),
            ],
            [
                'expression' => 'Dar en el clavo',
                'right_answer' => 'To find the right solution',
                'false_answer_one' => 'To accidentally hit something with a nail',
                'false_answer_two' => 'To make a mistake while attempting something',
                'language' => 'spanish',
                'created_by' => 'admin',
                'is_validated' => true,
                'created_at' => now(),
            ],
            [
                'expression' => 'Salirse con la suya',
                'right_answer' => 'To achieve your goal, against the wishes of others',
                'false_answer_one' => 'To abandon a project before completing it',
                'false_answer_two' => 'To face the consequences of an action',
                'language' => 'spanish',
                'created_by' => 'admin',
                'is_validated' => true,
                'created_at' => now(),
            ],
            [
                'expression' => 'Costar un ojo de la cara / Costar un riñón',
                'right_answer' => 'To be very expensive',
                'false_answer_one' => 'To experience great physical effort',
                'false_answer_two' => 'To have a high sentimental value',
                'language' => 'spanish',
                'created_by' => 'admin',
                'is_validated' => true,
                'created_at' => now(),
            ],
            [
                'expression' => 'Hablar por los codos',
                'right_answer' => 'To talk a lot or non-stop',
                'false_answer_one' => 'To speak through your elbows',
                'false_answer_two' => 'To communicate using gestures',
                'language' => 'spanish',
                'created_by' => 'admin',
                'is_validated' => true,
                'created_at' => now(),
            ],
            [
                'expression' => 'Tomar el pelo',
                'right_answer' => 'To tease or make fun of someone',
                'false_answer_one' => 'To brush your hair',
                'false_answer_two' => 'To help someone',
                'language' => 'spanish',
                'created_by' => 'admin',
                'is_validated' => true,
                'created_at' => now(),
            ],
            [
                'expression' => 'Eso es pan comido',
                'right_answer' => 'That is an easy task',
                'false_answer_one' => 'That is eaten bread',
                'false_answer_two' => 'That is a difficult task',
                'language' => 'spanish',
                'created_by' => 'admin',
                'is_validated' => true,
                'created_at' => now(),
            ],
            [
                'expression' => 'Tener algo en la punta de la lengua',
                'right_answer' => "When we know something but it doesn't come to us right away",
                'false_answer_one' => 'To be an eloquent speaker',
                'false_answer_two' => 'To remember something suddenly',
                'language' => 'spanish',
                'created_by' => 'admin',
                'is_validated' => true,
                'created_at' => now(),
            ],
            [
                'expression' => 'De tal palo, tal astilla',
                'right_answer' => 'To be similar to your parents',
                'false_answer_one' => 'To be a family of carpenters',
                'false_answer_two' => 'To have a good relation with your family',
                'language' => 'spanish',
                'created_by' => 'admin',
                'is_validated' => true,
                'created_at' => now(),
            ],
            [
                'expression' => 'Piece of cake',
                'right_answer' => 'Algo fácil de hacer',
                'false_answer_one' => 'Ser un trozo de tarta',
                'false_answer_two' => 'Algo complicado de hacer',
                'language' => 'english',
                'created_by' => 'admin',
                'is_validated' => true,
                'created_at' => now(),
            ],
            [
                'expression' => 'Cut to the chase',
                'right_answer' => 'Ir a lo importante',
                'false_answer_one' => 'Hacer una pausa',
                'false_answer_two' => 'Dejar de correr',
                'language' => 'english',
                'created_by' => 'admin',
                'is_validated' => true,
                'created_at' => now(),
            ],
            [
                'expression' => 'To cost an arm and a leg',
                'right_answer' => 'Cuando algo es muy caro',
                'false_answer_one' => 'Cuando algo te cuesta un brazo y una pierna',
                'false_answer_two' => 'Cuando algo necesita un esfuerzo físico',
                'language' => 'english',
                'created_by' => 'admin',
                'is_validated' => true,
                'created_at' => now(),
            ],
            [
                'expression' => 'To miss the boat',
                'right_answer' => 'Perder la oportunidad',
                'false_answer_one' => 'Perder el barco',
                'false_answer_two' => 'Perder el rumbo de la conversación',
                'language' => 'english',
                'created_by' => 'admin',
                'is_validated' => true,
                'created_at' => now(),
            ],
            [
                'expression' => 'Once in a blue moon',
                'right_answer' => 'Muy raramente',
                'false_answer_one' => 'Cada vez que la luna es azul',
                'false_answer_two' => 'Con mucha frecuencia',
                'language' => 'english',
                'created_by' => 'admin',
                'is_validated' => true,
                'created_at' => now(),
            ],
            [
                'expression' => 'To give someone the cold shoulder',
                'right_answer' => 'Ignorar a alguien',
                'false_answer_one' => 'Darle a alguien con el hombro frío',
                'false_answer_two' => 'Darle especial importancia a alguien',
                'language' => 'english',
                'created_by' => 'admin',
                'is_validated' => true,
                'created_at' => now(),
            ],
            [
                'expression' => 'To feel blue',
                'right_answer' => 'Estar triste',
                'false_answer_one' => 'Ser azul',
                'false_answer_two' => 'Estar eufórico',
                'language' => 'english',
                'created_by' => 'admin',
                'is_validated' => true,
                'created_at' => now(),
            ],
            [
                'expression' => 'Speak of the devil',
                'right_answer' => 'Cuando hablas de alguien y aparece',
                'false_answer_one' => 'Cuando hablas del diablo',
                'false_answer_two' => 'Cuando te pasa algo malo',
                'language' => 'english',
                'created_by' => 'admin',
                'is_validated' => true,
                'created_at' => now(),
            ],
            [
                'expression' => 'To not be rocket science',
                'right_answer' => 'Cuando una tarea no es difícil',
                'false_answer_one' => 'Cuando algo no es científico',
                'false_answer_two' => 'Cuando alguien no tiene un buen físico',
                'language' => 'english',
                'created_by' => 'admin',
                'is_validated' => true,
                'created_at' => now(),
            ],
            [
                'expression' => 'Break a leg!',
                'right_answer' => 'Se utiliza para desear suerte',
                'false_answer_one' => 'Cuando alguien se rompe una pierna',
                'false_answer_two' => 'Cuando pasa algo malo',
                'language' => 'english',
                'created_by' => 'admin',
                'is_validated' => true,
                'created_at' => now(),
            ],
        ]);
    }
}
