# fly.toml app configuration file generated for exprilliant on 2024-08-20T12:49:33+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'exprilliant'
primary_region = 'mad'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.1'

[env]
  APP_ENV = 'production'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  DB_CONNECTION = "pgsql"
  APP_DEBUG=true
  ASSET_URL='https://exprilliant.fly.dev/'
  APP_URL='https://exprilliant.fly.dev/'
  MAIL_MAILER='smtp'
  MAIL_HOST='mail.eclipso.de'
  MAIL_PORT=465
  MAIL_ENCRYPTION='SSL'
  MAIL_FROM_ADDRESS='luxcode@eclipso.eu'
  MAIL_FROM_NAME='exprilliant'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1