name: Exprilliant Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '21.7.3'
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, dom, fileinfo, sqlite3, pdo_sqlite
          coverage: none
      - name: Install dependencies
        run: npm ci
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress
      - name: Prepare environment
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: |
          cp .env.example .env
          php -r "file_exists('database/database.sqlite') || touch('database/database.sqlite');"
          sed -i "s#^APP_URL=.*#APP_URL=http://127.0.0.1:8000#" .env
          sed -i "s/^DB_CONNECTION=.*/DB_CONNECTION=sqlite/" .env
          sed -i "s#^DB_DATABASE=.*#DB_DATABASE=${DB_DATABASE}#" .env
          php artisan key:generate
      - name: Run database migrations and seeders
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan migrate:fresh --seed --no-interaction
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
